spring:
  jackson:
    default-property-inclusion: non_null
  cloud:
    openfeign:
      oauth2:
        enabled: true
        clientRegistrationId: twitch
      client:
        config:
          twitch-api:
            url: https://api.twitch.tv/helix
            loggerLevel: basic
            default-request-headers:
              Client-Id: "o7fi0jymm0qya6cijo2mr8w2lvppo1"
  security:
    oauth2:
      client:
        registration:
          twitch:
            authorization-grant-type: client_credentials
            client-authentication-method: client_secret_post
            client-id: "o7fi0jymm0qya6cijo2mr8w2lvppo1"
            client-secret: "cb6im72qggxho0i86iwnvpukge2wd4"
        provider:
          twitch:
            token-uri: https://id.twitch.tv/oauth2/token


  datasource:
    url: jdbc:mysql://${DATABASE_URL:localhost}:${DATABASE_PORT:3307}/twitch?createDatabaseIfNotExist=true
    username: ${DATABASE_USERNAME:root}
    password: ${DATABASE_PASSWORD:secret}
    driver-class-name: com.mysql.cj.jdbc.Driver

  sql:
    init:
      mode: always
      schema-locations: "classpath:database-init.sql"


logging:
  level:
    org.apache.coyote.http11.Http11InputBuffer: DEBUG # Incoming HTTP requests
    com.laioffer.twitch.external.TwitchApiClient: DEBUG # Outgoing HTTP requests
    org.springframework.jdbc.core: DEBUG # SQL




